### ISSUE TITLE
OOM killed error of  Operator Controller

### ISSUE THREAD

**Issue by superleo** [NVIDIA/aistore#128]
Problem: 
Hit OMM killed of operator controller on my k8s env

Cause:
1. Controller Manager resource limit in mem:30Mi
operator/config/manager/manager.yaml
```

        resources:
          limits:
            cpu: 100m
            memory: 30Mi
          requests:
            cpu: 100m
            memory: 20Mi
```
2. the memory usage average on 55Mi in the cluster.

Solution:
Modify the default memory limit to 100Mi
