### ISSUE TITLE
Cluster config not persisting after a reboot

### ISSUE THREAD

**Issue by arnaudbriche** [NVIDIA/aistore#194]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

Hi,

I run a single-node cluster using the cluster-minimal image.
My docker-compose file looks as follows:

```yaml
services:
  ais:
    image: arnaudbriche/aistorage-cluster-minimal:v3.26-d4a36ef2c522ddc4e1aeeef23857f2e70ebf215c
    restart: always
    environment:
      AWS_ACCESS_KEY_ID: ******
      AWS_SECRET_ACCESS_KEY: ******
      AWS_REGION: ******
      S3_ENDPOINT: ******
      AIS_BACKEND_PROVIDERS: aws
      AIS_AUTHN_ENABLED: true
      AIS_AUTHN_SECRET_KEY: ******
    ports:
      - '127.0.0.1:51080:51080'
    volumes:
      - /data/ais:/ais/disk0

  authn:
    image: aistorage/authn
    restart: always
    environment:
      AIS_AUTHN_ENABLED: true
      AIS_AUTHN_SECRET_KEY: ******
      AIS_AUTHN_PORT: 52001
      AIS_AUTHN_TTL: 0
      AIS_AUTHN_SU_NAME: ******
      AIS_AUTHN_SU_PASS: ******
    ports:
      - '127.0.0.1:52001:52001'
```

I created some bucket and proxy buckets and my setup is working well.
But when I restart the containers, I lose some of the cluster config: 
    - cluster id change
    - enabled features are no longer enabled
    - authn config disappears completely

How can I prevent this to happen ? 

### Expected Behavior

The config of the cluster does not change after a reboot.

### Current Behavior

Some of the config is missing after a reboot

### Steps To Reproduce

Using the docker-compose setup above

### AIStore build/version

Docker image built from this commit: d4a36ef2c522ddc4e1aeeef23857f2e70ebf215c

### Environment details (OS name and version, etc.)

linux, docker, docker-compose

**Comment by gaikwadabhishek** [comment]
Hey @arnaudbriche,

Docker containers are mainly for development and have limitations. For production, use a proper Kubernetes deployment of AIStore.

The AIS Operator manages stateful volumes that persist across restarts. Similarly, Authn deployments create PVs to retain state even with new deployments.

**Comment by arnaudbriche** [comment]
Hi @gaikwadabhishek ,

My use case is not really a production one, and I would rather not involve k8s for now.
Maybe just documenting where the state is store in the container would be enough.
It would allow users to use docker volumes to persist it.

**Comment by arnaudbriche** [comment]
Would just putting ```/etc/aisnode``` in a volume be enough to persist the state ?

**Comment by gaikwadabhishek** [comment]
I haven't run the docker-minimal setup in a while. You’ll likely need to mount the config directory to a local directory so that the state persists across restarts.

For AuthN, identify where the `authn.db` file is created and mount that location to a local directory to ensure the state is saved.

Maybe @rkoo19 can chime in—he’s worked on docker-minimal recently.

**Comment by gaikwadabhishek** [comment]
> `/tmp/ais`.

stores the data. I think config is `/etc/ais/` or `~./ais0/`, `~./ais1` and so on.

**Comment by gaikwadabhishek** [comment]
You can control where to store a config using a env var also @arnaudbriche

**Comment by rkoo19** [comment]
Hi @arnaudbriche, firstly, with regards to the environment variable to control where to store the config for AuthN, it will be `[AIS_AUTHN_CONF_DIR`](https://github.com/NVIDIA/aistore/blob/2ac6b70139d7b8085da911f3491055899ca540b0/docs/authn.md#authn-configuration-and-log).

**Comment by rkoo19** [comment]
> Hi [@arnaudbriche](https://github.com/arnaudbriche),
> 
> I wanted to provide some context as I work through this.
> 
> On closer examination, it seems that the `AIS_AUTHN_CONF_DIR` environment variable does not apply properly in the case of Docker deployments, mainly due to how the [`aistorage/authn image`](https://github.com/NVIDIA/aistore/blob/main/deploy/prod/k8s/authn_container/Dockerfile) is structured. The image has the `authn.json` configuration file baked into `/etc/ais/authn`, and this path is hardcoded in the entry point. Even if `AIS_AUTHN_CONF_DIR` is specified, the image does not populate the configuration file in the custom directory specified by this variable, and as a result, it does not work as expected.
> 
> [@gaikwadabhishek](https://github.com/gaikwadabhishek) [@aaronnw](https://github.com/aaronnw)

The way the image is currently structured, you can persist state by mounting a Docker Volume onto `/etc/ais/authn` or any directory specified by `AIS_AUTHN_CONF_DIR`. However, the mounted directory must be pre-populated with a valid configuration file. While the image pre-populates `/etc/ais/authn` by default, mounting a volume at that location overrides what was baked into the image, and custom directories specified by `AIS_AUTHN_CONF_DIR` are not populated automatically.

**Comment by arnaudbriche** [comment]
Thx @rkoo19 !

I ended up forced to use a very dirty docker compose setup with fixed IPs for each container as for some reason, if state is persisted and the docker compose restart is restarted (so container may have different internal IPs), the target cannot join the cluster as it's trying to reach it's old internal IP.

The setup in question is currently working and looks as follows:

```yaml
networks:
  vlan:
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1

volumes:
  ais_config: {}
  authn_config: {}

services:
  ais:
    image: arnaudbriche/aistorage-cluster-minimal:v3.26-d4a36ef2c522ddc4e1aeeef23857f2e70ebf215c
    restart: always
    environment:
      AWS_ACCESS_KEY_ID: REDACTED
      AWS_SECRET_ACCESS_KEY: REDACTED
      AWS_REGION: REDACTED
      S3_ENDPOINT: REDACTED
      AIS_BACKEND_PROVIDERS: aws
      AIS_AUTHN_ENABLED: true
      AIS_AUTHN_SECRET_KEY: REDACTED
    ports:
      - '127.0.0.1:51080:51080'
    networks:
      vlan:
        ipv4_address: 10.5.0.2
    volumes:
      - ais_config:/etc/aisnode
      - /data/ais:/ais/disk0

  authn:
    image: aistorage/authn
    restart: always
    environment:
      AIS_AUTHN_ENABLED: true
      AIS_AUTHN_SECRET_KEY: REDACTED
      AIS_AUTHN_PORT: 52001
      AIS_AUTHN_TTL: 0
      AIS_AUTHN_SU_NAME: REDACTED
      AIS_AUTHN_SU_PASS: REDACTED
    ports:
      - '127.0.0.1:52001:52001'
    networks:
      vlan:
        ipv4_address: 10.5.0.3
    volumes:
      - authn_config:/etc/ais
```

Hopefully there is a way to override the IP used to call the autoreg endpoint and I can get rid of the dirty static IP assignment in the docker compose file.
